name: dart_test_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

executables:
  dart_test_tools: dart_test_tools

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  coverage: ^1.7.2
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.24.0
