/// *** GENERATED FILE - ANY CHANGES WOULD BE OBSOLETE ON NEXT GENERATION *** ///
/// Generated by dart_test_tools (dtt)
/// repository: https://github.com/miyasic/dtt
/// Helper to test coverage for all project files
// ignore_for_file: unused_import

void main() {}
